version: '3'
services:
  mysql-server:
    image: mysql/mysql-server
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
  # postgres:
  #   image: postgres
  #   ports:
  #     - '5430:5432'
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_HOST_AUTH_METHOD: 'md5'
  #     POSTGRES_INITDB_ARGS: '--auth=md5'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3000:3000
